ral::cache::MetadataDictionary
std::map<std::string,std::string> ral::cache::MetadataDictionary::values
Stores the mapping of metdata label to metadata value
void ral::cache::MetadataDictionary::add_value(std::string key, std::string value)
Gets the type of CacheData that was used to construct this CacheData key The key in the map that we will be modifying. value The value that we will set the key to.
Referenced by ral::batch::PartwiseJoin::run, ral::batch::PartitionSingleNodeKernel::run, ral::batch::LimitKernel::run, ral::cache::distributing_kernel::send_message, ral::cache::distributing_kernel::send_total_partition_counts.
void ral::cache::MetadataDictionary::add_value(std::string key, int value)
Gets the type of CacheData that was used to construct this CacheData key The key in the map that we will be modifying. value The value that we will set the key to.
int ral::cache::MetadataDictionary::get_kernel_id()
Gets id of creating kernel. Get the id of the kernel that created this message.
void ral::cache::MetadataDictionary::print()
Print every key => value pair in the map. Only used for debugging purposes.
std::map<std::string,std::string> ral::cache::MetadataDictionary::get_values() const
Gets the map storing the metadata. the map storing all of the metadata.
Referenced by comm::message_receiver::message_receiver, ral::batch::PartitionSingleNodeKernel::run, ral::cache::distributing_kernel::send_message.
void ral::cache::MetadataDictionary::set_values(std::map< std::string, std::string > new_values)
Erases all current metadata and sets new values. new_values A map to copy into this->values .
bool ral::cache::MetadataDictionary::has_value(std::string key)
Checks if metadata has a specific key key The key to check if is in the metadata true if the key is in the metadata, otherwise return false
std::string ral::cache::MetadataDictionary::get_value(std::string key)
void ral::cache::MetadataDictionary::set_value(std::string key, std::string value)