ral::cache::distributing_kernel
const blazingdb::transport::Node& ral::cache::distributing_kernel::node
Stores the reference of the current node.
std::vector<std::map<std::string, std::atomic<size_t> > > ral::cache::distributing_kernel::node_count
Vector of maps that stores the message count associated to a node. Each vector corresponds to a message tracker. It's thread-safe.
std::vector<std::vector<std::string> > ral::cache::distributing_kernel::messages_to_wait_for
Vector of vectors of the messages registered to wait for. Each vector corresponds to a message tracker. It's thread-safe.
std::mutex ral::cache::distributing_kernel::messages_to_wait_for_mutex
ral::cache::distributing_kernel::distributing_kernel(std::size_t kernel_id, std::string expr, std::shared_ptr< Context > context, kernel_type kernel_type_id)
Constructor for the distributing_kernel kernel_id Current kernel identifier. expr Original logical expression that the kernel will execute. context Shared context associated to the running query. kernel_type_id Identifier representing the kernel type.
References ral::cache::kernel::kernel_id, ral::cache::kernel::context.
std::string ral::cache::distributing_kernel::kernel_name()
void ral::cache::distributing_kernel::set_number_of_message_trackers(std::size_t num_message_trackers)
Resizes the vector of the message trackers. Keeping more than one message tracker is useful for example for joins where we must keep track of separately for left and right partitions.
num_message_trackers The new number of the message trackers.
References ral::cache::kernel::context.
Referenced by ral::batch::PartitionSingleNodeKernel::run, ral::batch::SortAndSampleKernel::run, ral::batch::MergeStreamKernel::run.
void ral::cache::distributing_kernel::send_message(std::unique_ptr< ral::frame::BlazingTable > table, bool specific_cache, std::string cache_id, std::vector< std::string > target_ids, std::string message_id_prefix="", bool always_add=false, bool wait_for=false, std::size_t message_tracker_idx=0, ral::cache::MetadataDictionary extra_metadata={})
Sends a table with their corresponding metadata.
table The table to be sent. If table is a nullptr, an empty table is sent anyways. specific_cache Indicates if a message should be routed to a specific cache or to the global input cache. cache_id Indicates what cache a message should be routed to. target_id Vector of workers that will be receiving this message. message_id_prefix The prefix of the identifier of this message. always_add Forces to always add the table to the output cache. wait_for Indicates if this message must be registered to wait for back. message_tracker_idx The message tracker index. extra_metadata The cache identifier.
References ral::cache::MetadataDictionary::add_value, ral::cache::kernel::context, ral::cache::kernel::kernel_id, ral::cache::MetadataDictionary::get_values, ral::cache::kernel::output_cache, ral::cache::kernel::query_graph.
Referenced by ral::batch::PartitionSingleNodeKernel::run, ral::batch::LimitKernel::run, send_total_partition_counts, broadcast, scatter, scatterParts.
void ral::cache::distributing_kernel::scatter(std::vector< ral::frame::BlazingTableView > partitions, ral::cache::CacheMachine *output, std::string message_id_prefix, std::string cache_id, std::size_t message_tracker_idx=0)
Sends each partition to its corresponding nodes. It is assumed that the size of the vector is the same as the number of nodes.
partitions The table partitions to be sent. output The output cache. message_id_prefix The prefix of the identifier of this message. cache_id Indicates what cache a message should be routed to. message_tracker_idx The message tracker index.
References ral::cache::kernel::context, send_message.
void ral::cache::distributing_kernel::scatterParts(std::vector< ral::distribution::NodeColumnView > partitions, std::string message_id_prefix, std::vector< int32_t > part_ids)
Sends each partition to its corresponding nodes and corresponding part_id More than one partition can belong to the same node.
partitions The table partitions to be sent represented as node column views. message_id_prefix The prefix of the identifier of this message. part_ids A vector the same size as partitions, telling which part_id each partition corresponds to.
References send_message, ral::cache::kernel::add_to_output_cache.
Referenced by ral::batch::SortAndSampleKernel::run.
void ral::cache::distributing_kernel::broadcast(std::unique_ptr< ral::frame::BlazingTable > table, ral::cache::CacheMachine *output, std::string message_id_prefix, std::string cache_id, std::size_t message_tracker_idx=0, bool always_add=false)
Sends same table to all other nodes.
table The table to be broadcast output The output cache. message_id_prefix The prefix of the identifier of this message. cache_id Indicates what cache a message should be routed to. message_tracker_idx The message tracker index. always_add Forces to always send the message
References ral::cache::kernel::context, send_message.
Referenced by ral::batch::PartitionSingleNodeKernel::run.
void ral::cache::distributing_kernel::send_total_partition_counts(std::string message_id_prefix, std::string cache_id, std::size_t message_tracker_idx=0)
Sends the partition counter to all other nodes. These sent counters represent the number of messages that each node should wait on their end.
message_id_prefix The prefix of the identifier of this message. cache_id Indicates what cache a message should be routed to. message_tracker_idx The message tracker index.
References ral::cache::kernel::context, ral::cache::MetadataDictionary::add_value, send_message.
Referenced by ral::batch::PartitionKernel::run.
int ral::cache::distributing_kernel::get_total_partition_counts(std::size_t message_tracker_idx=0)
Get the total partition counters associated to a message tracker. The total counter returned by this function usually is the input for function WaitingQueue::wait_for_count() that allows waiting for the arrival of a certain number of messages.
message_tracker_idx The message tracker index.
References ral::cache::kernel::query_graph.
Referenced by ral::batch::PartitionKernel::run.
void ral::cache::distributing_kernel::increment_node_count(std::string node_id, std::size_t message_tracker_idx=0)
Increments by one the corresponding node counter associated to the node identifier and the message tracker identifier. Every time data is added to a cache, the node counter must be incremented by one.
node_id The node identifier. message_tracker_idx The message tracker index.
virtual ral::cache::distributing_kernel::~distributing_kernel()=default
Destructor