ral::cache::kernel
std::set<size_t> ral::cache::kernel::tasks
std::mutex ral::cache::kernel::kernel_mutex
std::condition_variable ral::cache::kernel::kernel_cv
std::atomic<std::size_t> ral::cache::kernel::total_input_bytes_processed
std::string ral::cache::kernel::expression
Stores the logical expression being processed.
Referenced by ral::batch::PartitionSingleNodeKernel::run, ral::batch::PartitionKernel::run, ral::batch::MergeStreamKernel::run, ral::batch::LimitKernel::run, ral::batch::BindableTableScan::BindableTableScan, ral::batch::BindableTableScan::run, ral::batch::Projection::Projection, ral::batch::Projection::run, ral::batch::Filter::Filter, ral::batch::UnionKernel::run, kernel.
port ral::cache::kernel::input_
Represents the input cache machines and their names.
Referenced by ral::batch::PartwiseJoin::run, ral::batch::JoinPartitionKernel::run, ral::batch::PartitionSingleNodeKernel::run, ral::batch::SortAndSampleKernel::run, ral::batch::PartitionKernel::run, ral::batch::MergeStreamKernel::run, ral::batch::OutputKernel::run, ral::batch::UnionKernel::run, input_cache.
port ral::cache::kernel::output_
Represents the output cache machine and their name.
Referenced by ral::batch::PartwiseJoin::run, ral::batch::PartitionSingleNodeKernel::run, ral::batch::TableScan::get_estimated_output_num_rows, ral::batch::BindableTableScan::get_estimated_output_num_rows, ral::batch::Filter::get_estimated_output_num_rows, output_cache, add_to_output_cache, estimate_output_bytes.
const std::size_t ral::cache::kernel::kernel_id
Stores the current kernel identifier.
Referenced by ral::batch::PartwiseJoin::run, ral::batch::PartitionSingleNodeKernel::run, ral::batch::SortAndSampleKernel::run, ral::batch::PartitionKernel::run, ral::batch::MergeStreamKernel::run, ral::batch::Filter::get_estimated_output_num_rows, ral::cache::distributing_kernel::distributing_kernel, ral::cache::distributing_kernel::send_message, kernel, input_cache, get_estimated_output_num_rows, process.
std::int32_t ral::cache::kernel::parent_id_
Stores the parent kernel identifier if any.
Referenced by kernel.
bool ral::cache::kernel::execution_done
Indicates whether the execution is complete.
kernel_type ral::cache::kernel::kernel_type_id
Stores the id of the kernel type.
Referenced by kernel.
std::shared_ptr<graph> ral::cache::kernel::query_graph
Stores a pointer to the current execution graph.
Referenced by ral::batch::PartwiseJoin::run, ral::batch::PartitionSingleNodeKernel::run, ral::batch::SortAndSampleKernel::run, ral::batch::PartitionKernel::run, ral::batch::MergeStreamKernel::run, ral::batch::TableScan::TableScan, ral::batch::BindableTableScan::BindableTableScan, ral::batch::Projection::Projection, ral::batch::Filter::Filter, ral::batch::Filter::get_estimated_output_num_rows, ral::cache::distributing_kernel::send_message, ral::cache::distributing_kernel::get_total_partition_counts, get_estimated_output_num_rows.
std::shared_ptr<Context> ral::cache::kernel::context
Shared context of the running query.
Referenced by ral::batch::PartwiseJoin::run, ral::batch::PartitionSingleNodeKernel::run, ral::batch::SortAndSampleKernel::run, ral::batch::PartitionKernel::run, ral::batch::MergeStreamKernel::run, ral::batch::TableScan::run, ral::batch::BindableTableScan::BindableTableScan, ral::batch::BindableTableScan::run, ral::batch::Projection::Projection, ral::batch::Projection::run, ral::batch::Filter::Filter, ral::batch::Filter::run, ral::batch::UnionKernel::run, ral::batch::ComputeWindowKernel::run, ral::cache::distributing_kernel::distributing_kernel, ral::cache::distributing_kernel::set_number_of_message_trackers, ral::cache::distributing_kernel::send_message, ral::cache::distributing_kernel::send_total_partition_counts, ral::cache::distributing_kernel::broadcast, ral::cache::distributing_kernel::scatter, kernel.
bool ral::cache::kernel::has_limit_
Indicates if the Logical plan only contains a LogicalTableScan (or BindableTableScan) and LogicalLimit.
Referenced by kernel.
int64_t ral::cache::kernel::limit_rows_
Specifies the maximum number of rows to return.
Referenced by kernel.
std::shared_ptr<spdlog::logger> ral::cache::kernel::logger
ral::cache::kernel::kernel(std::size_t kernel_id, std::string expr, std::shared_ptr< Context > context, kernel_type kernel_type_id)
Constructor for the kernel kernel_id Current kernel identifier. expr Original logical expression that the kernel will execute. context Shared context associated to the running query. kernel_type_id Identifier representing the kernel type.
References expression, kernel_id, parent_id_, kernel_type_id, context, has_limit_, limit_rows_, get_id, get_type_id.
void ral::cache::kernel::set_parent(size_t id)
Sets its parent kernel.
id The identifier of its parent.
bool ral::cache::kernel::has_parent() const
Indicates if the kernel has a parent.
true If the kernel has a parent, false otherwise.
virtual ral::cache::kernel::~kernel()
Destructor
virtual kstatus ral::cache::kernel::run()=0
Executes the batch processing. Loads the data from their input port, and after processing it, the results are stored in their output port.
kstatus 'stop' to halt processing, or 'proceed' to continue processing.
kernel_pair ral::cache::kernel::operator[](const std::string &portname)
std::int32_t ral::cache::kernel::get_id() const
Returns the kernel identifier.
int32_t The kernel identifier.
Referenced by ral::batch::PartwiseJoin::run, ral::batch::JoinPartitionKernel::run, ral::batch::PartitionSingleNodeKernel::run, ral::batch::SortAndSampleKernel::run, ral::batch::PartitionKernel::run, ral::batch::MergeStreamKernel::run, ral::batch::LimitKernel::run, ral::batch::BatchSequence::wait_for_next, ral::batch::TableScan::run, ral::batch::BindableTableScan::run, ral::batch::Projection::run, ral::batch::Filter::run, ral::batch::UnionKernel::run, ral::batch::ComputeWindowKernel::run, kernel, output_cache, input_cache, add_to_output_cache.
kernel_type ral::cache::kernel::get_type_id() const
Returns the kernel type identifier.
kernel_type The kernel type identifier.
Referenced by ral::batch::BatchSequence::wait_for_next, kernel.
void ral::cache::kernel::set_type_id(kernel_type kernel_type_id_)
Sets the kernel type identifier.
kernel_type The new kernel type identifier.
std::shared_ptr< ral::cache::CacheMachine > ral::cache::kernel::input_cache()
Returns the input cache.
References kernel_id, get_id, input_.
Referenced by ral::batch::SortAndSampleKernel::run, ral::batch::LimitKernel::run, ral::batch::Projection::run, ral::batch::Filter::run, ral::batch::Print::run, ral::batch::ComputeWindowKernel::run.
std::shared_ptr< ral::cache::CacheMachine > ral::cache::kernel::output_cache(std::string cache_id="")
Returns the output cache associated to an identifier.
cache_id The identifier of the output cache.
References get_id, output_.
Referenced by ral::batch::PartwiseJoin::run, ral::batch::PartitionSingleNodeKernel::run, ral::batch::SortAndSampleKernel::run, ral::batch::PartitionKernel::run, ral::batch::MergeStreamKernel::run, ral::batch::LimitKernel::run, ral::batch::TableScan::run, ral::batch::BindableTableScan::run, ral::batch::Projection::run, ral::batch::Filter::run, ral::batch::UnionKernel::run, ral::batch::ComputeWindowKernel::run, ral::cache::distributing_kernel::send_message.
bool ral::cache::kernel::add_to_output_cache(std::unique_ptr< ral::frame::BlazingTable > table, std::string cache_id="", bool always_add=false)
Adds a BlazingTable into the output cache.
table The table that will be added to the output cache. cache_id The cache identifier.
References get_message_id, get_id, output_.
Referenced by ral::batch::PartwiseJoin::run, ral::batch::PartitionSingleNodeKernel::run, ral::batch::TableScan::run, ral::batch::BindableTableScan::run, ral::batch::Projection::run, ral::batch::UnionKernel::run, ral::cache::distributing_kernel::scatterParts.
bool ral::cache::kernel::add_to_output_cache(std::unique_ptr< ral::cache::CacheData > cache_data, std::string cache_id="", bool always_add=false)
Adds a CacheData into the output cache.
cache_data The cache_data that will be added to the output cache. cache_id The cache identifier.
References get_message_id, get_id, output_.
bool ral::cache::kernel::add_to_output_cache(std::unique_ptr< ral::frame::BlazingHostTable > host_table, std::string cache_id="")
Adds a BlazingHostTable into the output cache.
host_table The host table that will be added to the output cache. cache_id The cache identifier.
References get_message_id, get_id, output_.
Context* ral::cache::kernel::get_context() const
Returns the current context.
std::string ral::cache::kernel::get_message_id()
Returns the id message as a string.
Referenced by add_to_output_cache.
bool ral::cache::kernel::input_all_finished()
Returns true if all the caches of an input are finished.
uint64_t ral::cache::kernel::total_input_rows_added()
Returns sum of all the rows added to all caches of the input port.
bool ral::cache::kernel::input_cache_finished(const std::string &port_name)
Returns true if a specific input cache is finished.
port_name Name of the port.
uint64_t ral::cache::kernel::input_cache_num_rows_added(const std::string &port_name)
Returns the number of rows added to a specific input cache.
port_name Name of the port.
std::pair< bool, uint64_t > ral::cache::kernel::get_estimated_output_num_rows()
Returns the estimated num_rows for the output, the default is that its the same as the input (i.e. project, sort, ...).
References query_graph, kernel_id.
ral::execution::task_result ral::cache::kernel::process(std::vector< std::unique_ptr< ral::frame::BlazingTable > > inputs, std::shared_ptr< ral::cache::CacheMachine > output, cudaStream_t stream, const std::map< std::string, std::string > &args)
Invokes the do_process function.
References do_process, kernel_id.
virtual ral::execution::task_result ral::cache::kernel::do_process(std::vector< std::unique_ptr< ral::frame::BlazingTable > >, std::shared_ptr< ral::cache::CacheMachine >, cudaStream_t, const std::map< std::string, std::string > &)
Implemented by all derived classes and is the function which actually performs transformations on dataframes.
inputs The data being operated on output the output cache to write the output to stream the cudastream to to use args any additional arguments the kernel may need to perform its execution that may not be available to the kernel at instantiation.
Referenced by process.
std::size_t ral::cache::kernel::estimate_output_bytes(const std::vector< std::unique_ptr< ral::cache::CacheData > > &inputs)
given the inputs, estimates the number of bytes that will be necessary for holding the output after performing a transformation. For many kernels this is not an estimate but rather a certainty. For operations whose outputs are of indeterminate size it provides an estimate.
inputs the data that would be transformed the number of bytes that we expect to be needed to hold the output after performing this kernels transformations on the given inputs.
References output_.
std::size_t ral::cache::kernel::estimate_operating_bytes(const std::vector< std::unique_ptr< ral::cache::CacheData > > &inputs)
given the inputs, estimates the number of bytes that will be necessary for performing the transformation. This can be thought of as the memory overhead of the actual transformations being performed. For many kernels this is not an estimate but rather a certainty. For operations that perform indeterminately sized allocations based on the contents of inputs it provides an estimate.
inputs the data that would be transformed the number of bytes that we expect to be needed to hold the output after performing this kernels transformations on the given inputs.
virtual std::string ral::cache::kernel::kernel_name()
void ral::cache::kernel::notify_complete(size_t task_id)
notify the kernel that a task it dispatched was completed successfully.
void ral::cache::kernel::notify_fail(size_t task_id)
notify the kernel that a task it dispatched failed.
void ral::cache::kernel::add_task(size_t task_id)
add a task to the list of tasks the kernel is waiting to complete.
bool ral::cache::kernel::finished_tasks()
check and see if all the tasks were completed.