ral::io::gdf_data_provider
std::vector<ral::frame::BlazingTableView> ral::io::gdf_data_provider::table_views
size_t ral::io::gdf_data_provider::current_file
stores an index to the current file being used
std::vector< std::map<std::string,std::string> > ral::io::gdf_data_provider::column_values
ral::io::gdf_data_provider::gdf_data_provider(std::vector< ral::frame::BlazingTableView > table_views, std::vector< std::map< std::string, std::string > > column_values)
std::shared_ptr< data_provider > ral::io::gdf_data_provider::clone() override
ral::io::gdf_data_provider::~gdf_data_provider()
bool ral::io::gdf_data_provider::has_next()
tells us if there are more files in the list of uris to be provided
Referenced by ral::io::uri_data_provider::get_some.
void ral::io::gdf_data_provider::reset()
Resets current_file to 0
data_handle ral::io::gdf_data_provider::get_next(bool open_file=true)
gets a randomaccessfile to the uri at file_uris[current_file] and advances current_file by 1 open_file = true will actually open the file and return a std::shared_ptr<arrow::io::RandomAccessFile>. If its false it will return a nullptr
Referenced by ral::io::uri_data_provider::get_some, ral::io::uri_data_provider::get_next.
std::vector< std::string > ral::io::gdf_data_provider::get_errors()
returns an empty vector. Used for compatiblity with apis that open files.
std::vector< data_handle > ral::io::gdf_data_provider::get_some(std::size_t num_files, bool open_file=true)
Tries to get up to num_files data_handles. We use this instead of a get_all() because if there are too many files, trying to get too many file handles will cause a crash. Using get_some() forces breaking up the process of getting file_handles. open_file = true will actually open the file and return a std::shared_ptr<arrow::io::RandomAccessFile>. If its false it will return a nullptr
References ral::io::dummy_data_provider::has_next, ral::io::dummy_data_provider::get_next.
void ral::io::gdf_data_provider::close_file_handles()
Does nothing. Used for compatiblity with apis that open files.Closes currently open set of file handles maintained by the provider
Referenced by ral::io::uri_data_provider::get_num_handles.
size_t ral::io::gdf_data_provider::get_num_handles()
Get the number of data_handles that will be provided.