ral::cache::CacheData
CacheDataType ral::cache::CacheData::cache_type
The CacheDataType that is used to store the dataframe representation.
std::vector<std::string> ral::cache::CacheData::col_names
A vector storing the names of the columns in the dataframe representation.
Referenced by ral::cache::ConcatCacheData::decache.
std::vector<cudf::data_type> ral::cache::CacheData::schema
A vector storing the cudf::data_type of the columns in the dataframe representation.
Referenced by ral::cache::ConcatCacheData::decache.
size_t ral::cache::CacheData::n_rows
Stores the number of rows in the dataframe representation.
MetadataDictionary ral::cache::CacheData::metadata
The metadata used for routing and planning.
Referenced by ral::cache::CPUCacheData::CPUCacheData.
ral::cache::CacheData::CacheData(CacheDataType cache_type, std::vector< std::string > col_names, std::vector< cudf::data_type > schema, size_t n_rows)
Constructor for CacheData This is only invoked by the derived classes when constructing. cache_type The CacheDataType of this cache letting us know where the data is stored. col_names The names of the columns in the dataframe. schema The types of the columns in the dataframe. n_rows The number of rows in the dataframe.
ral::cache::CacheData::CacheData()
virtual std::unique_ptr<ral::frame::BlazingTable> ral::cache::CacheData::decache()=0
Remove the payload from this CacheData. A pure virtual function. This removes the payload for the CacheData. After this the CacheData will almost always go out of scope and be destroyed. a BlazingTable generated from the source of data for this CacheData
virtual size_t ral::cache::CacheData::sizeInBytes() const =0
. A pure virtual function. This removes the payload for the CacheData. After this the CacheData will almost always go out of scope and be destroyed. the number of bytes our dataframe occupies in whatever format it is being stored
Referenced by ral::batch::PartwiseJoin::run.
virtual void ral::cache::CacheData::set_names(const std::vector< std::string > &names)=0
Set the names of the columns. names a vector of the column names.
virtual ral::cache::CacheData::~CacheData()
Destructor
std::vector<std::string> ral::cache::CacheData::names() const
Get the names of the columns. a vector of the column names
Referenced by ral::cache::CacheDataIO::decache.
std::vector<cudf::data_type> ral::cache::CacheData::get_schema() const
Get the cudf::data_type of each column. a vector of the cudf::data_type of each column.
size_t ral::cache::CacheData::num_columns() const
Get the number of columns this CacheData will generate with decache.
size_t ral::cache::CacheData::num_rows() const
Get the number of rows this CacheData will generate with decache.
Referenced by ral::batch::PartwiseJoin::run, ral::cache::CacheDataIO::decache.
CacheDataType ral::cache::CacheData::get_type() const
Gets the type of CacheData that was used to construct this CacheData The CacheDataType that is used to store the dataframe representation.
MetadataDictionary ral::cache::CacheData::getMetadata()
Get the MetadataDictionary The MetadataDictionary which is used in routing and planning.
Referenced by ral::batch::PartitionSingleNodeKernel::run.
std::unique_ptr< CacheData > ral::cache::CacheData::downgradeCacheData(std::unique_ptr< CacheData > cacheData, std::string id, std::shared_ptr< Context > ctx)
Utility function which can take a CacheData and if its a standard GPU cache data, it will downgrade it to CPU or Disk If the input CacheData is not of a type that can be downgraded, it will just return the original input, otherwise it will return the downgraded CacheData.