ral::batch::BatchSequence
std::shared_ptr<ral::cache::CacheMachine> ral::batch::BatchSequence::cache
Cache machine from which the data will be pulled.
const ral::cache::kernel* ral::batch::BatchSequence::kernel
Pointer to the kernel that will receive the cache data.
bool ral::batch::BatchSequence::ordered
Indicates whether the order should be kept when pulling data from the cache.
ral::batch::BatchSequence::BatchSequence(std::shared_ptr< ral::cache::CacheMachine > cache=nullptr, const ral::cache::kernel *kernel=nullptr, bool ordered=true)
Constructor for the BatchSequence cache The input cache from where the data will be pulled. kernel The kernel that will actually receive the pulled data. ordered Indicates whether the order should be kept at data pulling.
void ral::batch::BatchSequence::set_source(std::shared_ptr< ral::cache::CacheMachine > cache)
Updates the input cache machine. cache The pointer to the new input cache.
std::unique_ptr< ral::frame::BlazingTable > ral::batch::BatchSequence::next()
Get the next message as a unique pointer to a BlazingTable. If there are no more messages on the queue we get a nullptr. Unique pointer to a BlazingTable containing the next decached message.
Referenced by ral::batch::PartitionKernel::run, ral::batch::Print::run.
bool ral::batch::BatchSequence::wait_for_next()
Blocks executing thread until a new message is ready or when the message queue is empty. true A new message is ready. false There are no more messages on the cache.
References ral::cache::kernel::get_type_id, ral::cache::kernel::get_id.
Referenced by ral::batch::Print::run.
bool ral::batch::BatchSequence::has_next_now()
Indicates if the message queue is not empty at this point on time. true There is at least one message in the queue. false Message queue is empty.