{% set cuda_version='.'.join(environ.get('CUDA_VERSION', '9.2').split('.')[:2]) %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', '0') %}
{% set py_version=environ.get('CONDA_PY', '36') %}

package:
    name: blazingsql
    version: {{ version }}

build:
    number: {{ git_revision_count }}
    string: cuda{{ cuda_version + '_py' + py_version + '_' + git_revision_count }}
    script_env:
      - CUDA_VERSION
      - CUDACXX

source:
    path: ../../..

requirements:
    build:
        - gtest
        - gmock
        - google-cloud-cpp 1.16.0
        - cmake
        - cppzmq
        - python
        - pip
        - setuptools
        - spdlog >=1.7.0,<1.8.0
        - cython >=0.29,<0.30
        - openjdk >=8.0
        - maven
        - ninja
        - dask-cudf {{ minor_version }}.*
        - dask-cuda {{ minor_version }}.*
        - cudatoolkit {{ cuda_version }}.*
    host:
        - gtest
        - gmock
        - google-cloud-cpp 1.16.0
        - cmake
        - python
        - pip
        - setuptools
        - spdlog >=1.7.0,<1.8.0
        - cython >=0.29,<0.30
        - openjdk >=8.0
        - maven
        - ninja
        - dask-cudf {{ minor_version }}.*
        - dask-cuda {{ minor_version }}.*
        - cudatoolkit {{ cuda_version }}.*
    run:
        - gtest
        - google-cloud-cpp 1.16.0
        - cppzmq
        - openjdk >=8.0
        - jpype1
        - netifaces
        - pyhive
        - thrift 0.13.0
        - dask-cudf {{ minor_version }}.*
        - dask-cuda {{ minor_version }}.*
        - cudatoolkit {{ cuda_version }}.*

test:
    commands:
        python -c "import cio"

about:
    home: http://www.blazingsql.com/
    license: Apache-2.0
    license_family: Apache
