{% set cuda_version='.'.join(environ.get('CUDA_VERSION', '9.2').split('.')[:2]) %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set py_version=environ.get('CONDA_PY', 36) %}

package:
    name: blazingsql-python
    version: {{ version }}

build:
    number: {{ git_revision_count }}
    string: py{{ py_version }}_{{ git_revision_count }}

source:
    path: ../../..

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        #- python
        #- pip
        #- blazingsql-protocol  {{ version }}.*
        #- dask-cudf
    host:
        - python
        - pip
        - blazingsql-protocol  {{ version }}.*
        - dask-cudf
        - cudatoolkit {{ cuda_version }}.*
        - cmake
        
    run:
        - python
        - pip
        - blazingsql-protocol  {{ version }}.*
        - dask-cudf
       
about:
    home: http://www.blazingsql.com/
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
