# This is a basic workflow to help you get started with Actions

name: Build docs

# Controls when the action will run. 
on:
  push:
    branches: 
      - doxygen/graph
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: "apt -y install doxygen && pip install -U sphinx && pip install pydata-sphinx-theme recommonmark"
          build-command: "doxygen Doxyfile && make html"
          docs-folder: "docsrc/"
      - name: Commit documentation changes
        run: |
          git clone https://github.com/BlazingDB/BlazingSQL.git --branch doxygen/graph --single-branch doxygen/graph
          cp -a docsrc/_build/html/. docs/
          cp -a docsrc/html/. docs/api/
          cd docs
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          directory: docs
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
